### ISSUE TITLE
License is missing

### ISSUE THREAD

**Issue by notmatthancock** [sphinx-contrib/images#17]
What is the license for this repository? Missing license makes it unclear if/how this extension can be integrated and used within existing code bases.

**Comment by notmatthancock** [comment]
I apologize. I see now that the license is in fact specified in the `setup.py` file:

https://github.com/sphinx-contrib/images/blob/22b42190514be692f65958ed2cac821f5b9fc571/setup.py#L45

In that case, I will leave this issue open as a suggestion to add a LICENSE.txt to the repo itself.

**Comment by jonascj** [comment]
Fine suggestion, thank you. I'll add it to the next release, which will hopefully be completed in January 2021.

And setup.py also specifies it as version 2 of the license: https://choosealicense.com/licenses/apache-2.0/
