### ISSUE TITLE
New release on pypi.org

### ISSUE THREAD

**Issue by jonascj** [sphinx-contrib/images#2]
@t-b's PR (sphinx 2.0 port) was merged and we should now do a release on pypi.org.

Which version number should we go with? Semantic versioning would suggest 0.9.0 since the new version is not incompatible with older versions of sphinx. (I still don't quite believe we still support 1.1 and python 2.7, but we do, don't we?)

We should update the documentation to reflect the new version number, new project URLs etc. Should we move to readthedocs in the process? I'm not 100% sure how documentation ends up on https://pythonhosted.org/sphinxcontrib-images/.

**Comment by t-b** [comment]
CI at https://travis-ci.org/spinus/sphinxcontrib-images suggests that we still support python 2.7 and sphinx 1.1.3.

I would go with version 0.9.

Moving to readthedocs sounds like a good idea and killing https://pythonhosted.org/sphinxcontrib-images/.

But I would first do a new release and then start fixing and updating other things.

**Comment by jonascj** [comment]
Indeed, let us say 0.9 and do a release. I will see if I can get it done tonight. Then fix things other things after.

Sphinx 1.1.3 is ancient. Shouldn't we remove it from setup.py and tox.ini ?

**Comment by t-b** [comment]
> Sphinx 1.1.3 is ancient. Shouldn't we remove it from setup.py and tox.ini ?

Yes, let's remove it.

**Comment by jonascj** [comment]
I created a distribution and uploaded it to test.pypi.org : https://test.pypi.org/project/sphinxcontrib-images/

My own tests with a virtual python3.7 and python2.7 environment shows that package working with sphinx 2.3.1 and 1.8.5 respectively. 

The version 0.9.1 was forced because it took a second try to get it right (so 0.9.0 is also on test.pypi.org).

The way to create a distribution these days according to #python @ freenode is:

```
python3 setup.py sdist bdist_wheel
twine upload --repository-url https://test.pypi.org/legacy/ dist/
```
with a `setup.cfg` file containing:
```
[bdist_wheel]
universal = 1
```
I made a 0.9 branch here: https://github.com/sphinx-contrib/images/tree/0.9-release

Should we merge that and release?

**Comment by jonascj** [comment]
Alright, I think I managed to do a new release; 0.9.1 is now in PyPI (I forgot the lightbox2 submodule when I made the 0.9.0 release, so I had to bump to correct the mistake).

The docs have been lightly updated and moved to readthedocs. Maybe there is a slight problem with the version number here (right now it shows 0.8.0, but I think it is because it builds against an old version of the package):

https://sphinxcontrib-images.readthedocs.io/en/latest/
