### ISSUE TITLE
2023 release for newer versions of Python and Sphinx

### ISSUE THREAD

**Issue by 12rambau** [sphinx-contrib/images#33]
- [ ] #36
- [ ] maybe refresh the documentation (there are super nice themes out ther in the wild) 
- [ ] refresh readme (it's redundant with things in the documentation and I think it could be more synthetic 
- [ ] use some linters (black?, ruff?) in the github actions 
- [ ] use pre-commits ? 
- [ ] aline version support with Sphinx (>3.6) (and get access to hints, f string and other fancy stuff)

Let me know which one you like and I'll do specific PRs

**Comment by jonascj** [comment]
@12rambau I seem to have missed this one, so sorry for the late reply. 

I've taken the liberty to change the title to "2023 release for newer versions of Python and Sphinx". Let us discuss what to include in the next release.

**Comment by jonascj** [comment]
@12rambau I think the no. 1 priority should be to make a new release which is tested against Python 3.9+ and Sphinx 3.2.1+. 

But included in that release might as well be an update to the documentation (new theme, issue #35 and maybe more).

**Comment by jonascj** [comment]
Didn't happen, closing and trying for the same thing but in 2024 ...

**Comment by 12rambau** [comment]
sorry i got busy with other stuff and completely forgot to deal with it. I'll try to take a look as soon as possible
